CREATE DATABASE LETECH;
USE LETECH;
CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(100) NOT NULL);
CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(100) NOT NULL);
CREATE TABLE PROVINCIA(
    ID_PROVINCIA INT NOT NULL PRIMARY KEY,
    PROVINCIA VARCHAR(10) NOT NULL
);
CREATE TABLE CANTON(
    ID_CANTON INT NOT NULL PRIMARY KEY,
    CANTON VARCHAR(100) NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
);
CREATE TABLE DIRECCION(
    ID_DIRECCION INT NOT NULL PRIMARY KEY,
    ID_PROVINCIA INT NOT NULL,
    ID_CANTON INT NOT NULL,
    DIRECCION_GENERAL VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA),
    FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON)
);
CREATE TABLE SUCURSAL(
    ID_SUCURSAL INT NOT NULL PRIMARY KEY,
    ID_DIRECCION INT NOT NULL,
    TELEFONO INT NOT NULL,
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);
CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT NOT NULL PRIMARY KEY,
    PRODUCTO VARCHAR(100) NOT NULL,
    VALOR DOUBLE NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL
);
CREATE TABLE FACTURA(
    ID_FACTURA INT NOT NULL PRIMARY KEY,
	FECHA DATE NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
    FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);
CREATE TABLE DETALLE_FACTURA(
    ID_DETALLE_FACTURA INT NOT NULL PRIMARY KEY,
    ID_FACTURA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY(ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);
    